// <auto-generated />
using System;
using EmployeeSrever.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeSrever.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240409002911_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeServer.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "company1",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Name = "company2",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Name = "company3",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaleOrFmale")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            Identity = "123456789",
                            LastName = "Doe",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5792),
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Identity = "987654321",
                            LastName = "Smith",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5826),
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            Identity = "456789123",
                            LastName = "Johnson",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5828),
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1988, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            Identity = "111111111",
                            LastName = "Brown",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5830),
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1993, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            Identity = "222222222",
                            LastName = "Jones",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5832),
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1979, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            Identity = "333333333",
                            LastName = "Wilson",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5833),
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1996, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            Identity = "444444444",
                            LastName = "Taylor",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5835),
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1985, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            Identity = "555555555",
                            LastName = "Anderson",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5836),
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1983, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            Identity = "666666666",
                            LastName = "Martinez",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5839),
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1990, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            Identity = "777777777",
                            LastName = "Garcia",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5841),
                            Status = true
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1976, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Matthew",
                            Identity = "888888888",
                            LastName = "Rodriguez",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5842),
                            Status = true
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1991, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Isabella",
                            Identity = "999999999",
                            LastName = "Lopez",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5844),
                            Status = true
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1980, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethan",
                            Identity = "101010101",
                            LastName = "Hernandez",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5845),
                            Status = true
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1994, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ava",
                            Identity = "121212121",
                            LastName = "Gonzalez",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5847),
                            Status = true
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1989, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexander",
                            Identity = "131313131",
                            LastName = "Perez",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5849),
                            Status = true
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1987, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mia",
                            Identity = "141414141",
                            LastName = "Sanchez",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5851),
                            Status = true
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1992, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            Identity = "151515151",
                            LastName = "Ramirez",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5852),
                            Status = true
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1984, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charlotte",
                            Identity = "161616161",
                            LastName = "Torres",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5854),
                            Status = true
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1993, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            Identity = "171717171",
                            LastName = "Nguyen",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5855),
                            Status = true
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1982, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amelia",
                            Identity = "181818181",
                            LastName = "Kim",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5857),
                            Status = true
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1995, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            Identity = "191919191",
                            LastName = "Tran",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5862),
                            Status = true
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1986, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Harper",
                            Identity = "202020202",
                            LastName = "Chen",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5864),
                            Status = true
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1990, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jacob",
                            Identity = "212121212",
                            LastName = "Wang",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5865),
                            Status = true
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1981, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Evelyn",
                            Identity = "222222222",
                            LastName = "Wu",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(5867),
                            Status = true
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsManagementRole")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6032),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 1,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6034),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 1,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6036),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 2,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6037),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 2,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6038),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 2,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6040),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6041),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6042),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6044),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6046),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6047),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6049),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 4,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6050),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 4,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6052),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 4,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6053),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 5,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6054),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 5,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6056),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 5,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6057),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 6,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6059),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 6,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6060),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 6,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6061),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 7,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6063),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 7,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6064),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 7,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6065),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 8,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6066),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 8,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6068),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 9,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6069),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 9,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6070),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 10,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6072),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 10,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6073),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 11,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6074),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 11,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6076),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 11,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6077),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6078),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6080),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6082),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6083),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6084),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6086),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6087),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6088),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6089),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 14,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6091),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 14,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6092),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 14,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6093),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 15,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6095),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 15,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6096),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 15,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6100),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 16,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6101),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 16,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6102),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 16,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6104),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 17,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6105),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 17,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6106),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 17,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6108),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 18,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6109),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 18,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6110),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 19,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6112),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 19,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6113),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 20,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6114),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 20,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6116),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6117),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6118),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6120),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6121),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6123),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6124),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6125),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6127),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6128),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6129),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 5,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6130),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 6,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6132),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 24,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6133),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 24,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6134),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 24,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 4, 9, 3, 29, 10, 830, DateTimeKind.Local).AddTicks(6136),
                            IsManagementRole = false
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Developer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Designer"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Accountant"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Sales Representative"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Customer Service Representative"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "Human Resources Specialist"
                        },
                        new
                        {
                            RoleId = 7,
                            RoleName = "Marketing Coordinator"
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeServer.Core.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.EmployeeRole", b =>
                {
                    b.HasOne("EmployeeServer.Core.Entities.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeServer.Core.Entities.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Role", b =>
                {
                    b.Navigation("EmployeeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
