// <auto-generated />
using System;
using EmployeeSrever.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeSrever.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240410023350_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeServer.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "company1",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Name = "company2",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Name = "company3",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaleOrFmale")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1983, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3465),
                            FirstName = "David",
                            Identity = "000000001",
                            LastName = "Zimmerman",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3418),
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1980, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3477),
                            FirstName = "Batya",
                            Identity = "000000002",
                            LastName = "Cohen",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3475),
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1966, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3484),
                            FirstName = "Shoshana",
                            Identity = "000000003",
                            LastName = "Cohen",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 12, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3481),
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1989, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3490),
                            FirstName = "Batya",
                            Identity = "000000004",
                            LastName = "Stern",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3488),
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1995, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3495),
                            FirstName = "Joseph",
                            Identity = "000000005",
                            LastName = "Gross",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3493),
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1990, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3502),
                            FirstName = "Hannah",
                            Identity = "000000006",
                            LastName = "Schwartz",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3499),
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(2000, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3508),
                            FirstName = "Moses",
                            Identity = "000000007",
                            LastName = "Stern",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3506),
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1983, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3514),
                            FirstName = "Ruth",
                            Identity = "000000008",
                            LastName = "Goldberg",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3512),
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1985, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3519),
                            FirstName = "Esther",
                            Identity = "000000009",
                            LastName = "Gross",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3517),
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1973, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3526),
                            FirstName = "Solomon",
                            Identity = "000000010",
                            LastName = "Gordon",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 11, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3524),
                            Status = true
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(2004, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3532),
                            FirstName = "Moses",
                            Identity = "000000011",
                            LastName = "Friedman",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 12, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3530),
                            Status = true
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1977, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3538),
                            FirstName = "Isaac",
                            Identity = "000000012",
                            LastName = "Cohen",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3536),
                            Status = true
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1992, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3544),
                            FirstName = "Solomon",
                            Identity = "000000013",
                            LastName = "Schwartz",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3542),
                            Status = true
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1988, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3549),
                            FirstName = "Samuel",
                            Identity = "000000014",
                            LastName = "Goldberg",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3547),
                            Status = true
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1996, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3555),
                            FirstName = "Ruth",
                            Identity = "000000015",
                            LastName = "Blum",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 1, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3553),
                            Status = true
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1979, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3560),
                            FirstName = "Rachel",
                            Identity = "000000016",
                            LastName = "Stern",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 11, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3558),
                            Status = true
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1973, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3565),
                            FirstName = "Isaac",
                            Identity = "000000017",
                            LastName = "Geller",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3563),
                            Status = true
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(2004, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3571),
                            FirstName = "Aaron",
                            Identity = "000000018",
                            LastName = "Gordon",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3569),
                            Status = true
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1987, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3576),
                            FirstName = "Isaac",
                            Identity = "000000019",
                            LastName = "Stern",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3574),
                            Status = true
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1986, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3582),
                            FirstName = "Elijah",
                            Identity = "000000020",
                            LastName = "Sandler",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3580),
                            Status = true
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1991, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3587),
                            FirstName = "Miriam",
                            Identity = "000000021",
                            LastName = "Stern",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3585),
                            Status = true
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1971, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3592),
                            FirstName = "Ruth",
                            Identity = "000000022",
                            LastName = "Stern",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3590),
                            Status = true
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1968, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3625),
                            FirstName = "Batya",
                            Identity = "000000023",
                            LastName = "Zimmerman",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3622),
                            Status = true
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1991, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3632),
                            FirstName = "Leah",
                            Identity = "000000024",
                            LastName = "Sandler",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3629),
                            Status = true
                        },
                        new
                        {
                            Id = 25,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1987, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3637),
                            FirstName = "Aaron",
                            Identity = "000000025",
                            LastName = "Geller",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3635),
                            Status = true
                        },
                        new
                        {
                            Id = 26,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1992, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3643),
                            FirstName = "Hannah",
                            Identity = "000000026",
                            LastName = "Geller",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 1, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3641),
                            Status = true
                        },
                        new
                        {
                            Id = 27,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1968, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3648),
                            FirstName = "Rachel",
                            Identity = "000000027",
                            LastName = "Gross",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3646),
                            Status = true
                        },
                        new
                        {
                            Id = 28,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1965, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3654),
                            FirstName = "David",
                            Identity = "000000028",
                            LastName = "Segal",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3652),
                            Status = true
                        },
                        new
                        {
                            Id = 29,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1989, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3659),
                            FirstName = "Batya",
                            Identity = "000000029",
                            LastName = "Weiss",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3657),
                            Status = true
                        },
                        new
                        {
                            Id = 30,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1966, 4, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3664),
                            FirstName = "Shoshana",
                            Identity = "000000030",
                            LastName = "Cohen",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3663),
                            Status = true
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsManagementRole")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3418),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 1,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3418),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 1,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3418),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 2,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3475),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 2,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3475),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 12, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3481),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 12, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3481),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 12, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3481),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 4,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3488),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 4,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3488),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 4,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3488),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 5,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3493),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 5,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3493),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 6,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3499),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 6,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3499),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 7,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3506),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 7,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3506),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 7,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3506),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 8,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3512),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 8,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3512),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 9,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3517),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 9,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3517),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 10,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 11, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3524),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 10,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 11, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3524),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 10,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 11, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3524),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 11,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 12, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3530),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 11,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 12, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3530),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3536),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3536),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3536),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3542),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3542),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3542),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 14,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3547),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 14,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3547),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 14,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3547),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 15,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 1, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3553),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 15,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 1, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3553),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 15,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 1, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3553),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 16,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 11, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3558),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 16,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 11, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3558),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 17,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3563),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 17,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3563),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 18,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3569),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 18,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3569),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 18,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3569),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 19,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3574),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 19,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3574),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 19,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 3, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3574),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 20,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3580),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 20,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3580),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 20,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3580),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3585),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3585),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3585),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3590),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3590),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3590),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3622),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3622),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3622),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 24,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3629),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 24,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 7, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3629),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 25,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3635),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 25,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3635),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 25,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 9, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3635),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 26,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 1, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3641),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 26,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 1, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3641),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 27,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3646),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 27,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3646),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 27,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3646),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 28,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3652),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 28,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 6, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3652),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 29,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3657),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 29,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 2, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3657),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 30,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3663),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 30,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3663),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 30,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 10, 10, 5, 33, 50, 739, DateTimeKind.Local).AddTicks(3663),
                            IsManagementRole = true
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Developer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Designer"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Accountant"
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeServer.Core.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.EmployeeRole", b =>
                {
                    b.HasOne("EmployeeServer.Core.Entities.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeServer.Core.Entities.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Role", b =>
                {
                    b.Navigation("EmployeeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
