// <auto-generated />
using System;
using EmployeeSrever.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeSrever.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeServer.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "company1",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Name = "company2",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Name = "company3",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaleOrFmale")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1967, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4430),
                            FirstName = "Solomon",
                            Identity = "000000001",
                            LastName = "Stein",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4381),
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1999, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4441),
                            FirstName = "Jacob",
                            Identity = "000000002",
                            LastName = "Stern",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4439),
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1987, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4446),
                            FirstName = "Elijah",
                            Identity = "000000003",
                            LastName = "Levi",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 6, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4444),
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1970, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4451),
                            FirstName = "Jacob",
                            Identity = "000000004",
                            LastName = "Shapiro",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4449),
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(2006, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4455),
                            FirstName = "Aaron",
                            Identity = "000000005",
                            LastName = "Goldberg",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4453),
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1988, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4460),
                            FirstName = "Samuel",
                            Identity = "000000006",
                            LastName = "Stein",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4458),
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1976, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4465),
                            FirstName = "Isaac",
                            Identity = "000000007",
                            LastName = "Friedman",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4463),
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1986, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4469),
                            FirstName = "Aaron",
                            Identity = "000000008",
                            LastName = "Adler",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4467),
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1997, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4474),
                            FirstName = "Jacob",
                            Identity = "000000009",
                            LastName = "Klein",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 3, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4472),
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1992, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4481),
                            FirstName = "David",
                            Identity = "000000010",
                            LastName = "Zimmerman",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 1, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4479),
                            Status = true
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1993, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4486),
                            FirstName = "Samuel",
                            Identity = "000000011",
                            LastName = "Segal",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 12, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4484),
                            Status = true
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(2000, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4491),
                            FirstName = "Daniel",
                            Identity = "000000012",
                            LastName = "Segal",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4489),
                            Status = true
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1971, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4496),
                            FirstName = "Abraham",
                            Identity = "000000013",
                            LastName = "Stern",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4494),
                            Status = true
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1988, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4501),
                            FirstName = "Samuel",
                            Identity = "000000014",
                            LastName = "Adler",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4499),
                            Status = true
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(2003, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4506),
                            FirstName = "Isaac",
                            Identity = "000000015",
                            LastName = "Zimmerman",
                            MaleOrFmale = true,
                            StartDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4504),
                            Status = true
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1968, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4513),
                            FirstName = "Miriam",
                            Identity = "000000016",
                            LastName = "Weiss",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 5, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4511),
                            Status = true
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(2005, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4519),
                            FirstName = "Rebecca",
                            Identity = "000000017",
                            LastName = "Schwartz",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4518),
                            Status = true
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1973, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4525),
                            FirstName = "Leah",
                            Identity = "000000018",
                            LastName = "Blum",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4523),
                            Status = true
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(2003, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4530),
                            FirstName = "Ruth",
                            Identity = "000000019",
                            LastName = "Weiss",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4528),
                            Status = true
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1979, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4534),
                            FirstName = "Sarah",
                            Identity = "000000020",
                            LastName = "Segal",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4533),
                            Status = true
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1971, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4539),
                            FirstName = "Ruth",
                            Identity = "000000021",
                            LastName = "Levi",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4537),
                            Status = true
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1989, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4544),
                            FirstName = "Rebecca",
                            Identity = "000000022",
                            LastName = "Goldberg",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 7, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4542),
                            Status = true
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1985, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4549),
                            FirstName = "Shoshana",
                            Identity = "000000023",
                            LastName = "Stern",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 6, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4547),
                            Status = true
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1972, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4554),
                            FirstName = "Esther",
                            Identity = "000000024",
                            LastName = "Stern",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4552),
                            Status = true
                        },
                        new
                        {
                            Id = 25,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1971, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4558),
                            FirstName = "Sarah",
                            Identity = "000000025",
                            LastName = "Stein",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 1, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4556),
                            Status = true
                        },
                        new
                        {
                            Id = 26,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1966, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4563),
                            FirstName = "Esther",
                            Identity = "000000026",
                            LastName = "Rosenb0erg",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4561),
                            Status = true
                        },
                        new
                        {
                            Id = 27,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(1983, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4567),
                            FirstName = "Shoshana",
                            Identity = "000000027",
                            LastName = "Gordon",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4565),
                            Status = true
                        },
                        new
                        {
                            Id = 28,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(1968, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4572),
                            FirstName = "Leah",
                            Identity = "000000028",
                            LastName = "Gordon",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4570),
                            Status = true
                        },
                        new
                        {
                            Id = 29,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1985, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4576),
                            FirstName = "Esther",
                            Identity = "000000029",
                            LastName = "Katz",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4575),
                            Status = true
                        },
                        new
                        {
                            Id = 30,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(1968, 4, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4581),
                            FirstName = "Rebecca",
                            Identity = "000000030",
                            LastName = "Katz",
                            MaleOrFmale = false,
                            StartDate = new DateTime(2024, 3, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4579),
                            Status = true
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsManagementRole")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4381),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 1,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4381),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 2,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4439),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 2,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4439),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 2,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4439),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 6, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4444),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 3,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 6, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4444),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 4,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4449),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 4,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4449),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 5,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4453),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 5,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4453),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 5,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4453),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 6,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4458),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 6,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4458),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 7,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4463),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 7,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4463),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 8,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4467),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 8,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4467),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 9,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 3, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4472),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 9,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 3, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4472),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 10,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 1, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4479),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 10,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 1, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4479),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 10,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 1, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4479),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 11,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 12, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4484),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 11,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 12, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4484),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 11,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 12, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4484),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4489),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4489),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 12,
                            RoleId = 1,
                            EntryDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4489),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4494),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4494),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 13,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4494),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 14,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4499),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 14,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4499),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 15,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4504),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 15,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 11, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4504),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 16,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 5, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4511),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 16,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 5, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4511),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 17,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4518),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 17,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4518),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 17,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4518),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 18,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4523),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 18,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4523),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 19,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4528),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 19,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4528),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 20,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4533),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 20,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4533),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4537),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4537),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 21,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4537),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 7, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4542),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 7, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4542),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 22,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 7, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4542),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 6, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4547),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 23,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 6, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4547),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 24,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4552),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 24,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4552),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 24,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 10, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4552),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 25,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 1, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4556),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 25,
                            RoleId = 4,
                            EntryDate = new DateTime(2024, 1, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4556),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 26,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4561),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 26,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4561),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 26,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4561),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 27,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4565),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 27,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4565),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 27,
                            RoleId = 4,
                            EntryDate = new DateTime(2023, 8, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4565),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 28,
                            RoleId = 2,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4570),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 28,
                            RoleId = 3,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4570),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 28,
                            RoleId = 1,
                            EntryDate = new DateTime(2023, 9, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4570),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 29,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4575),
                            IsManagementRole = false
                        },
                        new
                        {
                            EmployeeId = 29,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 2, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4575),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 30,
                            RoleId = 2,
                            EntryDate = new DateTime(2024, 3, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4579),
                            IsManagementRole = true
                        },
                        new
                        {
                            EmployeeId = 30,
                            RoleId = 3,
                            EntryDate = new DateTime(2024, 3, 11, 3, 26, 48, 120, DateTimeKind.Local).AddTicks(4579),
                            IsManagementRole = true
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Developer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Designer"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Accountant"
                        });
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeServer.Core.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.EmployeeRole", b =>
                {
                    b.HasOne("EmployeeServer.Core.Entities.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeServer.Core.Entities.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("EmployeeServer.Core.Entities.Role", b =>
                {
                    b.Navigation("EmployeeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
